###############
### OPTIONS ###
###############

set-option -g default-shell /bin/zsh
  
# window numbers start at 1 rather than 0
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
  
# tmux messages are displayed for 4 seconds
set -g display-time 4000
 
# refresh 'status-left' and 'status-right' more often
set -g status-interval 5
 
# Modern true-colour
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*col*:Tc"

# set the tmux platform and version in the environment so we can use any results in later commands
run-shell "tmux setenv -g TMUX_PLATFORM $(uname)"
run-shell "tmux setenv -g TMUX_VERSION $(tmux -V | sed 's/tmux //')"
 
# stop waiting for command 0ms after ESC pressed
# (stops kak/vim from staying in insert mode for a delay after hitting ESC)
set -sg escape-time 0
 
# stop waiting for a command after ctrl-b after this time
# (prevents changing pane when pressing up/down in pane just after change of pane)
set-option -g repeat-time 100
 
# Enable mouse control (clickable windows, panes, resizable pane82
set -g mouse on
 
# don't rename windows automatically
set-option -g allow-rename off

# emacs key bindings in tmux command prompt (prefix + :) are better than
# vi keys, even for vim users
set -g status-keys emacs

# focus events enabled for terminals that support them
set -g focus-events on

# increase scrollback buffer size
set -g history-limit 1000000

# undercurl and underline colour support
set -ga terminal-overrides ",*:Smulx=\E[4::%p1%dm"
set -ga terminal-overrides ",*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%dm"

# Extended keys - enable shift/alt/ctrl combos properly in modern teminals 
set -g extended-keys on
set -ga terminal-features "*:extkeys" 


####################
### KEY BINDINGS ###
####################

# split panes using " for horiz and = for vert
bind '"' split-window -h -c "#{pane_current_path}"
bind = split-window -v -c "#{pane_current_path}"
unbind '%'
 
# move windows left and right in the window list with prefix + shift-left/right
bind-key '<' swap-window -t -1
bind-key '>' swap-window -t +1
 
# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf
 
# scroll pane up/down with shift-pageup/pagedown
# bind -n S-Pageup copy-mode -u
# bind -n S-Pagedown copy-mode -d

# rename window to basename of current pane's cwd
bind-key . run -b 'NEWNAME="#{pane_current_path}"; tmux rename-window "${NEWNAME####*/}"'


###############
### PLUGINS ###
###############

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'fabioluciano/tmux-powerkit'


####################################
### ACTIVITY MONITORING AND BELL ###
####################################

# enable activity monitoring
set-window-option -g monitor-activity on

# show message in status bar when there is activity in a non-focussed window
# best to leave off if you have claude or codex, thanks to their animations
set-option -g visual-activity off

# show status bar message when a bell occurs in a window
set-option -g visual-bell on

# notify when a monitored-for-silence window goes quiet
set-option -g visual-silence on

set-option -g bell-action other


#############
### THEME ###
#############

set -g @powerkit_theme "tokyo-night"
set -g @powerkit_theme_variant "night"
set -g @powerkit_status_position "bottom"
set -g @powerkit_plugins "datetime,memory"
set -g @powerkit_separator_style "slant"
set -g @powerkit_edge_separator_style "rounded"
set -g @powerkit_elements_spacing "false"
set -g @powerkit_status_interval "5"
set -g @powerkit_plugin_datetime_format "%H:%M:%S"


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
