set-option global startup_info_version 20260101

evaluate-commands %sh{
  # We're assuming the default bundle_path here...
  plugins="$kak_config/bundle"
  mkdir -p "$plugins"
  [ ! -e "$plugins/kak-bundle" ] && \
    git clone -q https://codeberg.org/jdugan6240/kak-bundle "$plugins/kak-bundle"
  printf "%s\n" "source '$plugins/kak-bundle/rc/kak-bundle.kak'"
}

bundle-noload kak-bundle https://codeberg.org/jdugan6240/kak-bundle

bundle-theme one.kak https://codeberg.org/raiguard/kak-one.git
bundle-install-hook one.kak %{
  mkdir -p "${kak_config}/colors"
  # Keep the symlink to the repo (not required, but convenient for discovery).
  ln -sf "${kak_opt_bundle_path}/one.kak" "${kak_config}/colors/"
  # Expose actual theme files where Kakoune expects them.
  for file in "${kak_opt_bundle_path}/one.kak/colors/"*.kak; do
    [ -e "$file" ] || continue
    ln -sf "$file" "${kak_config}/colors/$(basename "$file")"
  done
}
bundle-cleaner one.kak %{
  rm -f "${kak_config}/colors/one.kak"
  for file in "${kak_config}/colors/one-"*.kak; do
    [ -e "$file" ] || continue
    rm -f "$file"
  done
}

# best default colorscheme
# colorscheme desertex
# Try to load the theme if already installed; otherwise defer until after bootstrap.
try %{
    colorscheme one-dark
}

bundle powerline https://github.com/andreyorst/powerline.kak %{
    try %{
        require-module powerline
        powerline-theme gruvbox
        powerline-separator arrow
        powerline-toggle-module client
        powerline-start
    }
}

bundle fzf.kak https://github.com/andreyorst/fzf.kak %{
    map global user f %{:fzf-mode <ret>} -docstring "FZF mode"
}
bundle kakoune-snippets https://github.com/occivink/kakoune-snippets
bundle kakoune-vertical-selection https://github.com/occivink/kakoune-vertical-selection
bundle-customload kakoune-mouvre https://github.com/krornus/kakoune-mouvre %{
  # Minimal load: needed for search-no-wrap (kakoune-cargo dependency).
  source "%opt{bundle_path}/kakoune-mouvre/mouvre.kak"
}
bundle-customload kakoune-cargo https://github.com/krornus/kakoune-cargo %{
  source "%opt{bundle_path}/kakoune-cargo/cargo.kak"
  # Make cleanup hooks resilient when no highlighters exist.
  try %{ remove-hooks global cargo-compiler }
  hook -group cargo-compiler global WinSetOption compiler=(?!cargo).* %{
    try %{ remove-highlighter window/cargo }
    remove-hooks window cargo-hooks
  }
}

bundle kak-lsp https://github.com/kak-lsp/kak-lsp %{
    try %{ declare-user-mode lsp }
    map global user l %{:enter-user-mode lsp<ret>} -docstring "LSP mode"
    map global lsp d ':lsp-definition<ret>' -docstring 'definition'
    map global lsp r ':lsp-references<ret>' -docstring 'references'
    map global lsp t ':lsp-type-definition<ret>' -docstring 'type definition'
    map global lsp i ':lsp-implementation<ret>' -docstring 'implementation'
    map global lsp h ':lsp-hover<ret>' -docstring 'hover docs'
    map global lsp R ':lsp-rename<ret>' -docstring 'rename'
    map global lsp n ':lsp-find-error --include-warnings<ret>' -docstring 'next diagnostic'
    map global lsp p ':lsp-find-error --previous --include-warnings<ret>' -docstring 'prev diagnostic'

    set-option global lsp_diagnostic_line_error_sign '!'
    set-option global lsp_diagnostic_line_warning_sign '?'
    set-option global lsp_diagnostic_line_info_sign 'i'
    set-option global lsp_diagnostic_line_hint_sign 'h'

    lsp-enable
    lsp-diagnostic-lines-enable global
    lsp-inline-diagnostics-enable global
    hook -always global KakEnd .* lsp-exit
}
bundle-install-hook kak-lsp %{
  cargo install --locked --force --path .
}
bundle-cleaner kak-lsp %{
  rm ~/.cargo/bin/kak-lsp
}


# Bootstrap missing bundles on first startup and provide lightweight status.
hook global KakBegin .* %{
  evaluate-commands %sh{
    marker="$kak_opt_bundle_path/.bootstrap-ok"
    fail_marker="$kak_opt_bundle_path/.bootstrap-failed"
    needs_install=0
    if [ -f "$fail_marker" ]; then
      needs_install=1
    fi
    for plug in $kak_opt_bundle_plugins; do
      if [ ! -d "$kak_opt_bundle_path/$plug" ]; then
        needs_install=1
        break
      fi
      case "$plug" in
        kak-bundle|one.kak) continue ;;
      esac
      if [ ! -f "$kak_opt_bundle_path/$plug-load.kak" ]; then
        needs_install=1
        break
      fi
    done

    if [ "$needs_install" -eq 1 ]; then
      printf "%s\n" "echo -markup {yellow}kak-bundle: installing missing plugins...{default}"
      printf "%s\n" "bundle-install"
      exit 0
    fi

    if [ ! -f "$marker" ]; then
      touch "$marker"
    fi

    if ! command -v kak-lsp >/dev/null 2>&1; then
      printf "%s\n" "echo -debug 'kak-lsp not found (LSP disabled until installed)'"
    fi
    if ! command -v rust-analyzer >/dev/null 2>&1; then
      printf "%s\n" "echo -debug 'rust-analyzer not found (Rust LSP may not start)'"
    fi
  }
}

# After bundle-install completes, load new plugins in this session.
hook global User bundle-after-install %{
  evaluate-commands %sh{
    marker="$kak_opt_bundle_path/.bootstrap-ok"
    fail_marker="$kak_opt_bundle_path/.bootstrap-failed"
    if [ -z "$kak_opt_bundle_plugins_to_install" ]; then
      exit 0
    fi
    if [ "$kak_opt_bundle_succeeded" = "true" ]; then
      touch "$marker"
      rm -f "$fail_marker"
      for plug in $kak_opt_bundle_plugins_to_install; do
        case "$plug" in
          kak-bundle|one.kak|kak-lsp) continue ;;
        esac
        load="$kak_opt_bundle_path/$plug-load.kak"
        if [ -f "$load" ]; then
          printf "try %%{ source '%s' }\n" "$load"
        fi
      done
      if [ -f "$kak_config/colors/one-dark.kak" ]; then
        printf "%s\n" "colorscheme one-dark"
      fi
      printf "%s\n" "echo -markup {green}kak-bundle: plugins ready.{default}"
    else
      rm -f "$marker"
      touch "$fail_marker"
      printf "%s\n" "info -title 'kak-bundle' 'Install/update failed. See *bundle-status*.'"
    fi
  }
}



# show line numbers
addhl global/ number-lines

# shw matching brackets
addhl global/ show-matching

# highlight 80th column background gray
addhl global/ column 80 default,rgb:404040

set global indentwidth 4
set global tabstop 4
set global ui_options ncurses_assistant=none

# kakoune-snippets: don't auto trigger
try %{
    set-option global snippets_auto_expand false
    map global insert <a-space> '<a-;>: snippets-expand-trigger %{exec "b"}<ret>'
    map global insert <a-n> '<a-;>: snippets-select-next-placeholders<ret>'
}

# eslint
hook global WinSetOption filetype=javascript %{
    set buffer lintcmd 'eslint --config .eslintrc.js --format=node_modules/eslint-formatter-kakoune'
    lint-enable
    lint
}

# prettier
hook global WinSetOption filetype=javascript %{
    set buffer formatcmd 'prettier --parser=babel'
    lint-enable
    lint
}

# kakoune-cargo
hook -group make-rust global WinSetOption filetype=rust %[
    set-option window makecmd cargo
    set-option global compiler cargo
]

# keys for vertical-selection.kak
try %{
    map global normal <a-V> :select-up<ret>
    map global normal <a-v> :select-down<ret>
    map global normal V :select-vertically<ret>
}

# keys for phantom selection
try %{
    map global normal <a-f> ": phantom-sel-iterate-next<ret>"
    map global normal <a-F> ": phantom-sel-select-all; phantom-sel-clear<ret>"
}

# press hash to comment line
map global normal '#' ':comment-line<ret>'

# enter command mode with ; instead of :
map global normal ';' ':' 

# ~/Software/kakoune-buffers Buffer control mappings
try %{
    hook global WinDisplay .* %{ try %{ info-buffers } }
    map global user b ':enter-buffers-mode<ret>'            -docstring 'buffers…'
    map global user B ':enter-user-mode -lock buffers<ret>' -docstring 'buffers (lock)…'
}

map global normal <backspace> <space> -docstring 'remove all sels except main'
map global normal <a-backspace> <a-space> -docstring 'remove main sel'

# ~/Software/kakoune-cd CD mappings
try %{
    map global goto d '<esc>:change-directory-current-buffer<ret>' -docstring 'current buffer dir'
    map global goto r '<esc>:change-directory-project-root<ret>' -docstring 'project root dir'
    map global goto p '<esc>:cd ..;print-working-directory<ret>' -docstring 'parent dir'
    map global user e ':edit-current-buffer-directory<ret>' -docstring 'edit in current buffer dir'
    alias global cdd change-directory-current-buffer
    alias global cdr change-directory-project-root
    alias global pwd print-working-directory
    alias global ecd edit-current-buffer-directory
}

# FZF plugin configuration
evaluate-commands %sh{
  if command -v fzf >/dev/null 2>&1; then
    printf "%s\n" "map global normal <c-p> ': fzf-mode<ret>'"
  else
    printf "%s\n" "echo -debug 'fzf not found (fzf.kak mapping disabled)'"
  fi
}

# FZF performance and filtering tweaks.
hook global ModuleLoaded fzf %{
    # Faster startup: avoid heavy previews by default.
    set-option global fzf_preview false
    set-option global fzf_file_preview false
    # Use ripgrep for file lists and ignore VCS internals.
    set-option global fzf_file_command "rg --files --hidden -g '!.git/**'"
}

# Rust QoL: ignore target/ in fzf file search.
hook global BufSetOption filetype=rust %{
    set-option buffer fzf_file_command "rg --files --hidden -g '!.git/**' -g '!target/**' -g '!**/target/**'"
}

# Tmux integration: split panes and attach a new Kakoune client to this session.
try %{ declare-user-mode tmux }
map global user t ':enter-user-mode tmux<ret>' -docstring 'tmux…'
map global normal <c-k> ':enter-user-mode tmux<ret>' -docstring 'tmux…'

define-command -docstring "tmux-split-vertical: split pane side-by-side and attach to current session." tmux-split-vertical %{
  evaluate-commands %sh{
    if [ -z "${kak_client_env_TMUX:-}" ] || ! command -v tmux >/dev/null 2>&1; then
      printf "%s\n" "echo -debug 'tmux not available'"
      exit 0
    fi

    session="$kak_session"
    bufname="$kak_bufname"
    buffile="$kak_buffile"
    cwd="$PWD"
    if [ -n "$buffile" ]; then
      cwd=$(dirname "$buffile")
      open_cmd="edit -existing -- \"$buffile\""
    else
      open_cmd="buffer \"$bufname\""
    fi
    open_cmd=$(printf "%s" "$open_cmd" | sed 's/\"/\\\\\"/g')

    tmux split-window -h -c "$cwd" "kak -c \"$session\" -e \"$open_cmd\""
  }
}

define-command -docstring "tmux-split-horizontal: split pane top/bottom and attach to current session." tmux-split-horizontal %{
  evaluate-commands %sh{
    if [ -z "${kak_client_env_TMUX:-}" ] || ! command -v tmux >/dev/null 2>&1; then
      printf "%s\n" "echo -debug 'tmux not available'"
      exit 0
    fi

    session="$kak_session"
    bufname="$kak_bufname"
    buffile="$kak_buffile"
    cwd="$PWD"
    if [ -n "$buffile" ]; then
      cwd=$(dirname "$buffile")
      open_cmd="edit -existing -- \"$buffile\""
    else
      open_cmd="buffer \"$bufname\""
    fi
    open_cmd=$(printf "%s" "$open_cmd" | sed 's/\"/\\\\\"/g')

    tmux split-window -v -c "$cwd" "kak -c \"$session\" -e \"$open_cmd\""
  }
}

define-command -docstring "tmux-split-vertical-fzf: split pane side-by-side and open fzf-file." tmux-split-vertical-fzf %{
  evaluate-commands %sh{
    if [ -z "${kak_client_env_TMUX:-}" ] || ! command -v tmux >/dev/null 2>&1; then
      printf "%s\n" "echo -debug 'tmux not available'"
      exit 0
    fi

    session="$kak_session"
    cwd="$PWD"
    if [ -n "$kak_buffile" ]; then
      cwd=$(dirname "$kak_buffile")
    fi

    tmux split-window -h -c "$cwd" "kak -c \"$session\" -e \"require-module fzf-file; fzf-file\""
  }
}

define-command -docstring "tmux-split-horizontal-fzf: split pane top/bottom and open fzf-file." tmux-split-horizontal-fzf %{
  evaluate-commands %sh{
    if [ -z "${kak_client_env_TMUX:-}" ] || ! command -v tmux >/dev/null 2>&1; then
      printf "%s\n" "echo -debug 'tmux not available'"
      exit 0
    fi

    session="$kak_session"
    cwd="$PWD"
    if [ -n "$kak_buffile" ]; then
      cwd=$(dirname "$kak_buffile")
    fi

    tmux split-window -v -c "$cwd" "kak -c \"$session\" -e \"require-module fzf-file; fzf-file\""
  }
}

map global tmux '=' ':tmux-split-vertical<ret>' -docstring 'split vertical (same buffer)'
map global tmux '"' ':tmux-split-horizontal<ret>' -docstring 'split horizontal (same buffer)'
map global tmux 'v' ':tmux-split-vertical-fzf<ret>' -docstring 'split vertical (fzf file)'
map global tmux 's' ':tmux-split-horizontal-fzf<ret>' -docstring 'split horizontal (fzf file)'

# keys for goto-file.kak autoloaded plugin
try %{
    map global goto f '<esc>Lgoto-file<ret>' -docstring 'file'
    map global goto F f -docstring 'file (legacy)'
}

# use # to comment line and a-# to comment block
map global normal '#' :comment-line<ret> -docstring 'comment line'
map global normal '<a-#>' :comment-block<ret> -docstring 'comment block'

# Cross-platform clipboard integration.
evaluate-commands %sh{
  if command -v pbcopy >/dev/null 2>&1 && command -v pbpaste >/dev/null 2>&1; then
    copy_cmd="pbcopy"
    paste_cmd="pbpaste"
  elif command -v wl-copy >/dev/null 2>&1 && command -v wl-paste >/dev/null 2>&1; then
    copy_cmd="wl-copy"
    paste_cmd="wl-paste --no-newline"
  elif command -v xsel >/dev/null 2>&1; then
    copy_cmd="xsel --input --clipboard"
    paste_cmd="xsel --output --clipboard"
  else
    printf "%s\n" "echo -debug 'no clipboard helper found (pbcopy/pbpaste, wl-copy/wl-paste, xsel)'"
    exit 0
  fi

  printf "%s\n" "hook global NormalKey y|d|c %{ nop %sh{ printf %s \\\"\\$kak_main_reg_dquote\\\" | $copy_cmd } }"
  printf "%s\n" "map global user P '!$paste_cmd<ret>'"
  printf "%s\n" "map global user p '<a-!>$paste_cmd<ret>'"
  printf "%s\n" "map global insert <a-p> '<a-;>P'"
}

map global insert <tab>   '<a-;><gt>'
map global insert <s-tab> '<a-;><lt>'

hook global InsertCompletionShow .* %{
     try %{
            # this command temporarily removes cursors preceded by whitespace;
            # if there are no cursors left, it raises an error, does not
            # continue to execute the mapping commands, and the error is eaten
            # by the `try` command so no warning appears.
            execute-keys -draft 'h<a-K>\h<ret>'
            map window insert <tab> <c-n>
            map window insert <s-tab> <c-p>
            #map window insert <ret> <right>
      }
}

hook global InsertCompletionHide .* %{
    unmap window insert <tab> <c-n>
    unmap window insert <s-tab> <c-p>
    unmap window insert <ret> <right>
}
